import { createClient } from "tinacms/dist/client";
import autogeneratedClient from "./__generated__/client";

const client = createClient({
  ...autogeneratedClient,
  branch:
    process.env.GITHUB_BRANCH ||
    process.env.VERCEL_GIT_COMMIT_REF ||
    process.env.HEAD ||
    "main",
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID!,
  token: process.env.TINA_TOKEN!,
});

export default client;
